kind: pipeline
name: container-packer

steps:

- name: the more you know
  image: alpine:3.8
  commands:
  - env | sort

- name: check for accidentally dropped creds
  image: yellowmegaman/container-trufflehog:2.0.98
  commands:
  - /usr/local/bin/trufflehog --regex --entropy=False file:///$CI_WORKSPACE

- name: pack
  image: docker:18.09.0
  environment:
    DOCKER_HOST: tcp://serviced:2375
    FROM_IMAGE: "docker:18.06"
    PACKER_VERSION: 1.3.3
    PROJECT_NAME: yellowmegaman
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
    QUAY_USERNAME:
      from_secret: quay_username
    QUAY_PASSWORD:
      from_secret: quay_password
  commands:
  - apk --no-cache add unzip wget
  - wget https://releases.hashicorp.com/packer/1.3.3/packer_1.3.3_linux_amd64.zip -qO packer.zip
  - unzip -q packer.zip
  - mv packer /usr/bin/
  - packer build "$DRONE_REPO_NAME".json

services:
- name: serviced
  image: plugins/docker
  entrypoint: [ dockerd ]
  command: [ '-H', 'tcp://0.0.0.0:2375', '--iptables=false' ]
